# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [14]:
import pandas as pd

url1 = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'
url2 = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv'
url3 = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv'

df1 = pd.read_csv(url1)
df2 = pd.read_csv(url2)
df3 = pd.read_csv(url3)

In [23]:
df_final = df1, df2, df3

In [24]:
df_final

(     Customer          ST GENDER             Education  \
 0     RB50392  Washington    NaN                Master
 1     QZ44356     Arizona      F              Bachelor
 2     AI49188      Nevada      F              Bachelor
 3     WW63253  California      M              Bachelor
 4     GA49547  Washington      M  High School or Below
 ...       ...         ...    ...                   ...
 4003      NaN         NaN    NaN                   NaN
 4004      NaN         NaN    NaN                   NaN
 4005      NaN         NaN    NaN                   NaN
 4006      NaN         NaN    NaN                   NaN
 4007      NaN         NaN    NaN                   NaN

      Customer Lifetime Value   Income  Monthly Premium Auto  \
 0                        NaN      0.0                1000.0
 1                 697953.59%      0.0                  94.0
 2                1288743.17%  48767.0                 108.0
 3                 764586.18%      0.0                 106.0
 4                 536307.65%  36357.0                  68.0
 ...                      ...      ...                   ...
 4003                     NaN      NaN                   NaN
 4004                     NaN      NaN                   NaN
 4005                     NaN      NaN                   NaN
 4006                     NaN      NaN                   NaN
 4007                     NaN      NaN                   NaN

      Number of Open Complaints     Policy Type  Vehicle Class  \
 0                       1/0/00   Personal Auto  Four-Door Car
 1                       1/0/00   Personal Auto  Four-Door Car
 2                       1/0/00   Personal Auto   Two-Door Car
 3                       1/0/00  Corporate Auto            SUV
 4                       1/0/00   Personal Auto  Four-Door Car
 ...                        ...             ...            ...
 4003                       NaN             NaN            NaN
 4004                       NaN             NaN            NaN
 4005                       NaN             NaN            NaN
 4006                       NaN             NaN            NaN
 4007                       NaN             NaN            NaN

       Total Claim Amount
 0               2.704934
 1            1131.464935
 2             566.472247
 3             529.881344
 4              17.269323
 ...                  ...
 4003                 NaN
 4004                 NaN
 4005                 NaN
 4006                 NaN
 4007                 NaN

 [4008 rows x 11 columns],
     Customer          ST GENDER Education Customer Lifetime Value  Income  \
 0    GS98873     Arizona      F  Bachelor              323912.47%   16061
 1    CW49887  California      F    Master              462680.11%   79487
 2    MY31220  California      F   College              899704.02%   54230
 3    UH35128      Oregon      F   College             2580706.30%   71210
 4    WH52799     Arizona      F   College              380812.21%   94903
 ..       ...         ...    ...       ...                     ...     ...
 991  HV85198     Arizona      M    Master              847141.75%   63513
 992  BS91566     Arizona      F   College              543121.91%   58161
 993  IL40123      Nevada      F   College              568964.41%   83640
 994  MY32149  California      F    Master              368672.38%       0
 995  SA91515  California      M  Bachelor              399258.39%       0

      Monthly Premium Auto Number of Open Complaints  Total Claim Amount  \
 0                      88                    1/0/00          633.600000
 1                     114                    1/0/00          547.200000
 2                     112                    1/0/00          537.600000
 3                     214                    1/1/00         1027.200000
 4                      94                    1/0/00          451.200000
 ..                    ...                       ...                 ...
 991                    70                    1/0/00          185.667213
 992                    68                    1/0/00          140.747286
 993                    70                    1/0/00          471.050488
 994                    96                    1/0/00           28.460568
 995                   111                    1/0/00          700.349052

         Policy Type  Vehicle Class
 0     Personal Auto  Four-Door Car
 1      Special Auto            SUV
 2     Personal Auto   Two-Door Car
 3     Personal Auto     Luxury Car
 4    Corporate Auto   Two-Door Car
 ..              ...            ...
 991   Personal Auto  Four-Door Car
 992  Corporate Auto  Four-Door Car
 993  Corporate Auto   Two-Door Car
 994   Personal Auto   Two-Door Car
 995   Personal Auto            SUV

 [996 rows x 11 columns],
      Customer       State  Customer Lifetime Value             Education  \
 0     SA25987  Washington              3479.137523  High School or Below
 1     TB86706     Arizona              2502.637401                Master
 2     ZL73902      Nevada              3265.156348              Bachelor
 3     KX23516  California              4455.843406  High School or Below
 4     FN77294  California              7704.958480  High School or Below
 ...       ...         ...                      ...                   ...
 7065  LA72316  California             23405.987980              Bachelor
 7066  PK87824  California              3096.511217               College
 7067  TD14365  California              8163.890428              Bachelor
 7068  UP19263  California              7524.442436               College
 7069  Y167826  California              2611.836866               College

      Gender  Income  Monthly Premium Auto  Number of Open Complaints  \
 0         M       0                   104                          0
 1         M       0                    66                          0
 2         F   25820                    82                          0
 3         F       0                   121                          0
 4         M   30366                   101                          2
 ...     ...     ...                   ...                        ...
 7065      M   71941                    73                          0
 7066      F   21604                    79                          0
 7067      M       0                    85                          3
 7068      M   21941                    96                          0
 7069      M       0                    77                          0

          Policy Type  Total Claim Amount  Vehicle Class
 0      Personal Auto          499.200000   Two-Door Car
 1      Personal Auto            3.468912   Two-Door Car
 2      Personal Auto          393.600000  Four-Door Car
 3      Personal Auto          699.615192            SUV
 4      Personal Auto          484.800000            SUV
 ...              ...                 ...            ...
 7065   Personal Auto          198.234764  Four-Door Car
 7066  Corporate Auto          379.200000  Four-Door Car
 7067  Corporate Auto          790.784983  Four-Door Car
 7068   Personal Auto          691.200000  Four-Door Car
 7069  Corporate Auto          369.600000   Two-Door Car

 [7070 rows x 11 columns])

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [1]:
# Your code goes here

import pandas as pd

# Load the dataset
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"
df = pd.read_csv(url)

# Display the first few rows of the dataset
print(df.head())

# Display the basic information of the dataset
print(df.info())

# Display the summary statistics for numerical columns
print(df.describe().transpose())

# Display the summary statistics for categorical columns
print(df.describe(include=['object']).transpose())

# Check for missing values
print(df.isnull().sum())

# Option 1: Drop rows with missing values
df_cleaned = df.dropna()

# Option 2: Fill missing values with appropriate values (mean, median, mode, etc.)
# For demonstration, let's fill numerical columns with their mean and categorical columns with their mode
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
categorical_columns = df.select_dtypes(include=['object']).columns

for col in numerical_columns:
    df[col].fillna(df[col].mean(), inplace=True)

for col in categorical_columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

print(df.isnull().sum())  # Check if missing values are handled

   unnamed:_0 customer       state  customer_lifetime_value response  \
0           0  DK49336     Arizona              4809.216960       No
1           1  KX64629  California              2228.525238       No
2           2  LZ68649  Washington             14947.917300       No
3           3  XL78013      Oregon             22332.439460      Yes
4           4  QA50777      Oregon              9025.067525       No

   coverage education effective_to_date employmentstatus gender  ...  \
0     Basic   College        2011-02-18         Employed      M  ...
1     Basic   College        2011-01-18       Unemployed      F  ...
2     Basic  Bachelor        2011-02-10         Employed      M  ...
3  Extended   College        2011-01-11         Employed      M  ...
4   Premium  Bachelor        2011-01-17    Medical Leave      F  ...

   number_of_policies     policy_type        policy  renew_offer_type  \
0                   9  Corporate Auto  Corporate L3            Offer3
1                   1   Personal Auto   Personal L3            Offer4
2                   2   Personal Auto   Personal L3            Offer3
3                   2  Corporate Auto  Corporate L3            Offer2
4                   7   Personal Auto   Personal L2            Offer1

   sales_channel  total_claim_amount  vehicle_class  vehicle_size  \
0          Agent          292.800000  Four-Door Car       Medsize
1    Call Center          744.924331  Four-Door Car       Medsize
2    Call Center          480.000000            SUV       Medsize
3         Branch          484.013411  Four-Door Car       Medsize
4         Branch          707.925645  Four-Door Car       Medsize

  vehicle_type month
0            A     2
1            A     1
2            A     2
3            A     1
4            A     1

[5 rows x 27 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB
None
                                 count          mean           std  \
unnamed:_0                     10910.0   5454.500000   3149.590053
customer_lifetime_value        10910.0   8018.241094   6885.081434
income                         10910.0  37536.284785  30359.195670
monthly_premium_auto           10910.0     93.196059     34.442532
months_since_last_claim        10910.0     15.149071      9.783520
months_since_policy_inception  10910.0     48.091934     27.940675
number_of_open_complaints      10910.0      0.384256      0.885589
number_of_policies             10910.0      2.979193      2.399359
total_claim_amount             10910.0    434.888330    292.180556
month                          10910.0      1.466728      0.498915

                                       min          25%           50%  \
unnamed:_0                        0.000000  2727.250000   5454.500000
customer_lifetime_value        1898.007675  4014.453113   5771.147235
income                            0.000000     0.000000  33813.500000
monthly_premium_auto             61.000000    68.000000     83.000000
months_since_last_claim           0.000000     7.000000     15.000000
months_since_policy_inception     0.000000    24.000000     48.000000
number_of_open_complaints         0.000000     0.000000      0.000000
number_of_policies                1.000000     1.000000      2.000000
total_claim_amount                0.099007   271.082527    382.564630
month                             1.000000     1.000000      1.000000

                                        75%           max
unnamed:_0                      8181.750000  10909.000000
customer_lifetime_value         8992.779137  83325.381190
income                         62250.750000  99981.000000
monthly_premium_auto             109.000000    298.000000
months_since_last_claim           23.000000     35.000000
months_since_policy_inception     71.000000     99.000000
number_of_open_complaints          0.384256      5.000000
number_of_policies                 4.000000      9.000000
total_claim_amount               547.200000   2893.239678
month                              2.000000      2.000000
                   count unique            top   freq
customer           10910   9134        ID89933      7
state              10910      5     California   4183
response           10910      2             No   9444
coverage           10910      3          Basic   6660
education          10910      5       Bachelor   3272
effective_to_date  10910     59     2011-01-10    239
employmentstatus   10910      5       Employed   6789
gender             10910      2              F   5573
location_code      10910      3       Suburban   6902
marital_status     10910      3        Married   6319
policy_type        10910      3  Personal Auto   8128
policy             10910      9    Personal L3   4118
renew_offer_type   10910      4         Offer1   4483
sales_channel      10910      4          Agent   4121
vehicle_class      10910      6  Four-Door Car   5834
vehicle_size       10910      3        Medsize   7873
vehicle_type       10910      1              A  10910
unnamed:_0                       0
customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64
unnamed:_0                       0
customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64

In [2]:
# Convert columns to appropriate data types if needed
# For example, if 'Income' was read as an object, we should convert it to a numerical type
df['Income'] = pd.to_numeric(df['Income'], errors='coerce')

# Ensure date columns are in datetime format if applicable
# df['SomeDateColumn'] = pd.to_datetime(df['SomeDateColumn'], errors='coerce')

print(df.dtypes)

KeyError: 'Income'

In [3]:
# Rename columns for consistency and readability
df.rename(columns={
    'Customer': 'CustomerID',
    'ST': 'State',
    'Gender': 'Gender',
    'Education': 'Education',
    'Customer Lifetime Value': 'CustomerLifetimeValue',
    'Income': 'Income',
    'Monthly Premium Auto': 'MonthlyPremiumAuto',
    'Number of Open Complaints': 'OpenComplaints',
    'Policy Type': 'PolicyType',
    'Vehicle Class': 'VehicleClass',
    'Total Claim Amount': 'TotalClaimAmount',
    # Add any additional columns that need renaming
}, inplace=True)

print(df.columns)

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

In [4]:
# Example: Create a new column for 'Annual Premium Auto'
df['AnnualPremiumAuto'] = df['MonthlyPremiumAuto'] * 12

print(df.head())

KeyError: 'MonthlyPremiumAuto'

In [5]:
# Save the cleaned dataset to a new CSV file
df.to_csv('cleaned_marketing_customer_analysis.csv', index=False)

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here